[application]

[web.app]

# HTML title tag content
title = "Bank!"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
resources = ["assets/main.css", "assets/header.svg", "**/*.png"]
identifier = "dev.stormyyy"
publisher = "stormyyy"
icon = ["icons/icon.ico"]